### ISSUE TITLE
Cursor position misaligned in Atom 0.117.0

### ISSUE THREAD

**Issue by macfanatic** [teddybradford/atom-trendy-light-ui#4]
I just upgraded to Atom 0.117.0 and I'm experiencing several bugs while selecting text and cursor placement with this theme.  Switching to one of the bundled themes resolves the issue.

See attached screenshot - what is represented in the browser is vastly different than what is actually in the file.  Doing things such as a find/replace are broken as well in those dialogs, since the cursor barely moves as the characters are typed in.

Simply pasting into a blank document works, but as soon as I paste the contents into a file with syntax highlighting, it's busted.

![screen shot 2015-02-10 at 8 19 35 am](https://cloud.githubusercontent.com/assets/162970/6127851/aec22d68-b0fd-11e4-859b-6d77ce80341f.png)

```
$('form:not(.skip-dirty-tracking):not(#q_search)').AreYouSure()
```

**Comment by teddybradford** [comment]
I suspect a lot of these bugs are due to changes in Atom. I created a pull request to merge changes made in atom-dark-ui to this theme, but there are several conflicts that need to be combed through. Unfortunately at the moment I don't have time to go through them.

**Comment by macfanatic** [comment]
Figured it was a non-trivial task, I might try to figure out what's going on myself. Haven't themed Atom yet, so this could be a good place to start. I really liked your theme :)

**Comment by teddybradford** [comment]
I'm glad you like the theme so much! You are welcome to work on it and submit pull requests. :)

**Comment by maqdev** [comment]
I fixed the cursor placement with this theme removing this style from theme sources: `text-rendering: optimizeLegibility`
Please also take a look at this thread: https://github.com/atom/atom/issues/5384

Nice theme, kudos!

**Comment by thiagodebastos** [comment]
https://github.com/teddybradford/atom-trendy-light-ui/issues/4#issuecomment-74485753
This fixed it for me, thank you @maqdev

**Comment by teddybradford** [comment]
Is this still an issue? I can't seem to find `optimizeLegibility` in the codebase.
